function A = computeFrogA(in1)
%COMPUTEFROGA
%    A = COMPUTEFROGA(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Apr-2020 10:07:12

q0 = in1(:,8);
q2 = in1(:,1);
q3 = in1(:,2);
q4 = in1(:,3);
q5 = in1(:,4);
q6 = in1(:,5);
t2 = cos(q0);
t3 = sin(q0);
t4 = q0+q4;
t5 = q0+q5;
t8 = -q0;
t9 = -q4;
t10 = -q5;
t6 = q3+t4;
t7 = q6+t5;
t12 = -t2;
t13 = -t3;
t14 = q0+t9;
t15 = q0+t10;
t16 = q3+q4+t8;
t17 = q5+q6+t8;
t18 = t2.*(3.0./1.0e+1);
t19 = t3.*(3.0./1.0e+1);
t11 = q2+t6;
t20 = cos(t16);
t21 = cos(t17);
t22 = q2+t16;
t23 = sin(t16);
t24 = sin(t17);
t25 = cos(t22);
t26 = sin(t22);
t27 = t20./2.0;
t28 = t21./4.0;
t29 = t23./2.0;
t30 = t24./4.0;
t31 = -t28;
t32 = -t29;
t33 = t25.*(3.0./1.0e+1);
t34 = t26.*(3.0./1.0e+1);
t35 = -t33;
A = reshape([t34,t32+t34,t32+t34-sin(t14)./2.0,0.0,0.0,t12,t3,t19+sin(t4)./2.0-sin(t6)./2.0+sin(t11).*(3.0./1.0e+1),t35,t27+t35,t27+t35-cos(t14)./2.0,0.0,0.0,t13,t12,-t18-cos(t4)./2.0+cos(t6)./2.0-cos(t11).*(3.0./1.0e+1),0.0,0.0,0.0,t30-sin(t15).*(2.0./5.0),t30,t12,t3,-t19+sin(t5).*(2.0./5.0)+sin(t7)./4.0,0.0,0.0,0.0,t31-cos(t15).*(2.0./5.0),t31,t13,t12,t18-cos(t5).*(2.0./5.0)-cos(t7)./4.0],[8,4]);
